source 'https://rubygems.org'

gem 'combine_pdf'
gem 'middleman', '4.3.5'
gem 'middleman-autoprefixer', '2.10.1'
gem 'pdfkit'
gem 'redcarpet'
gem 'song_pro'
gem 'wkhtmltopdf-binary'
gem 'mab'
gem 'chord_diagrams'
