source 'https://rubygems.org'

gem 'chordpro', git: 'https://github.com/spilth/chordpro'
gem 'combine_pdf'
gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-s3_sync'
gem 'pdfkit'
gem 'redcarpet'
gem 'song_pro', git: 'https://github.com/spilth/song_pro', ref: 'cd08ff0'
gem 'wkhtmltopdf-binary'
